package: tmdbproxyoapimodel
generate:
  gin-server: true
  strict-server: true
  models: true
output-options:
  include-operation-ids:
    - find-by-id
    - search-movie
    - movie-details
    - movie-external-ids
    - search-tv
    - tv-series-details
    - tv-series-external-ids
    - authentication-validate-key
  disable-type-aliases-for-type: []
  skip-prune: true  

output: oapi/raw/oapi-gen-strict.go