# jupyter/base-notebook
FROM quay.io/jupyter/base-notebook


RUN mamba install --yes pandas pymongo plotly black jupyterlab_code_formatter && \
    mamba clean --all -f -y && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"

USER ${NB_UID}