package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"

	"github.com/rraymondgh/arr-interface/internal/gql"
	"github.com/rraymondgh/arr-interface/internal/gql/gqlmodel/gen"
)

// System is the resolver for the system field.
func (r *queryResolver) System(ctx context.Context) (gen.SystemQuery, error) {
	return gen.SystemQuery{Version: "very early", Download: false}, nil
}

// Query returns gql.QueryResolver implementation.
func (r *Resolver) Query() gql.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
