// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package gqlclient

import (
	"context"

	"github.com/Khan/genqlient/graphql"
	"github.com/rraymondgh/arr-interface/internal/protocol"
)

type ContentType string

const (
	ContentTypeMovie     ContentType = "movie"
	ContentTypeTvShow    ContentType = "tv_show"
	ContentTypeMusic     ContentType = "music"
	ContentTypeEbook     ContentType = "ebook"
	ContentTypeComic     ContentType = "comic"
	ContentTypeAudiobook ContentType = "audiobook"
	ContentTypeGame      ContentType = "game"
	ContentTypeSoftware  ContentType = "software"
	ContentTypeXxx       ContentType = "xxx"
)

// TorrentContentResponse is returned by TorrentContent on success.
type TorrentContentResponse struct {
	TorrentContentByID TorrentContentTorrentContentByID `json:"torrentContentByID"`
}

// GetTorrentContentByID returns TorrentContentResponse.TorrentContentByID, and is useful for accessing the field via an interface.
func (v *TorrentContentResponse) GetTorrentContentByID() TorrentContentTorrentContentByID {
	return v.TorrentContentByID
}

// TorrentContentTorrentContentByID includes the requested fields of the GraphQL type TorrentContentByID.
type TorrentContentTorrentContentByID struct {
	Id TorrentContentTorrentContentByIDIdTorrentContentSearchResult `json:"id"`
}

// GetId returns TorrentContentTorrentContentByID.Id, and is useful for accessing the field via an interface.
func (v *TorrentContentTorrentContentByID) GetId() TorrentContentTorrentContentByIDIdTorrentContentSearchResult {
	return v.Id
}

// TorrentContentTorrentContentByIDIdTorrentContentSearchResult includes the requested fields of the GraphQL type TorrentContentSearchResult.
type TorrentContentTorrentContentByIDIdTorrentContentSearchResult struct {
	Items []TorrentContentTorrentContentByIDIdTorrentContentSearchResultItemsTorrentContent `json:"items"`
}

// GetItems returns TorrentContentTorrentContentByIDIdTorrentContentSearchResult.Items, and is useful for accessing the field via an interface.
func (v *TorrentContentTorrentContentByIDIdTorrentContentSearchResult) GetItems() []TorrentContentTorrentContentByIDIdTorrentContentSearchResultItemsTorrentContent {
	return v.Items
}

// TorrentContentTorrentContentByIDIdTorrentContentSearchResultItemsTorrentContent includes the requested fields of the GraphQL type TorrentContent.
type TorrentContentTorrentContentByIDIdTorrentContentSearchResultItemsTorrentContent struct {
	InfoHash    protocol.ID                                                                             `json:"infoHash"`
	Torrent     TorrentContentTorrentContentByIDIdTorrentContentSearchResultItemsTorrentContentTorrent  `json:"torrent"`
	ContentType ContentType                                                                             `json:"contentType"`
	Content     TorrentContentTorrentContentByIDIdTorrentContentSearchResultItemsTorrentContentContent  `json:"content"`
	Episodes    TorrentContentTorrentContentByIDIdTorrentContentSearchResultItemsTorrentContentEpisodes `json:"episodes"`
}

// GetInfoHash returns TorrentContentTorrentContentByIDIdTorrentContentSearchResultItemsTorrentContent.InfoHash, and is useful for accessing the field via an interface.
func (v *TorrentContentTorrentContentByIDIdTorrentContentSearchResultItemsTorrentContent) GetInfoHash() protocol.ID {
	return v.InfoHash
}

// GetTorrent returns TorrentContentTorrentContentByIDIdTorrentContentSearchResultItemsTorrentContent.Torrent, and is useful for accessing the field via an interface.
func (v *TorrentContentTorrentContentByIDIdTorrentContentSearchResultItemsTorrentContent) GetTorrent() TorrentContentTorrentContentByIDIdTorrentContentSearchResultItemsTorrentContentTorrent {
	return v.Torrent
}

// GetContentType returns TorrentContentTorrentContentByIDIdTorrentContentSearchResultItemsTorrentContent.ContentType, and is useful for accessing the field via an interface.
func (v *TorrentContentTorrentContentByIDIdTorrentContentSearchResultItemsTorrentContent) GetContentType() ContentType {
	return v.ContentType
}

// GetContent returns TorrentContentTorrentContentByIDIdTorrentContentSearchResultItemsTorrentContent.Content, and is useful for accessing the field via an interface.
func (v *TorrentContentTorrentContentByIDIdTorrentContentSearchResultItemsTorrentContent) GetContent() TorrentContentTorrentContentByIDIdTorrentContentSearchResultItemsTorrentContentContent {
	return v.Content
}

// GetEpisodes returns TorrentContentTorrentContentByIDIdTorrentContentSearchResultItemsTorrentContent.Episodes, and is useful for accessing the field via an interface.
func (v *TorrentContentTorrentContentByIDIdTorrentContentSearchResultItemsTorrentContent) GetEpisodes() TorrentContentTorrentContentByIDIdTorrentContentSearchResultItemsTorrentContentEpisodes {
	return v.Episodes
}

// TorrentContentTorrentContentByIDIdTorrentContentSearchResultItemsTorrentContentContent includes the requested fields of the GraphQL type Content.
type TorrentContentTorrentContentByIDIdTorrentContentSearchResultItemsTorrentContentContent struct {
	Id         string                                                                                                             `json:"id"`
	Source     string                                                                                                             `json:"source"`
	Attributes []TorrentContentTorrentContentByIDIdTorrentContentSearchResultItemsTorrentContentContentAttributesContentAttribute `json:"attributes"`
}

// GetId returns TorrentContentTorrentContentByIDIdTorrentContentSearchResultItemsTorrentContentContent.Id, and is useful for accessing the field via an interface.
func (v *TorrentContentTorrentContentByIDIdTorrentContentSearchResultItemsTorrentContentContent) GetId() string {
	return v.Id
}

// GetSource returns TorrentContentTorrentContentByIDIdTorrentContentSearchResultItemsTorrentContentContent.Source, and is useful for accessing the field via an interface.
func (v *TorrentContentTorrentContentByIDIdTorrentContentSearchResultItemsTorrentContentContent) GetSource() string {
	return v.Source
}

// GetAttributes returns TorrentContentTorrentContentByIDIdTorrentContentSearchResultItemsTorrentContentContent.Attributes, and is useful for accessing the field via an interface.
func (v *TorrentContentTorrentContentByIDIdTorrentContentSearchResultItemsTorrentContentContent) GetAttributes() []TorrentContentTorrentContentByIDIdTorrentContentSearchResultItemsTorrentContentContentAttributesContentAttribute {
	return v.Attributes
}

// TorrentContentTorrentContentByIDIdTorrentContentSearchResultItemsTorrentContentContentAttributesContentAttribute includes the requested fields of the GraphQL type ContentAttribute.
type TorrentContentTorrentContentByIDIdTorrentContentSearchResultItemsTorrentContentContentAttributesContentAttribute struct {
	Key    string `json:"key"`
	Source string `json:"source"`
	Value  string `json:"value"`
}

// GetKey returns TorrentContentTorrentContentByIDIdTorrentContentSearchResultItemsTorrentContentContentAttributesContentAttribute.Key, and is useful for accessing the field via an interface.
func (v *TorrentContentTorrentContentByIDIdTorrentContentSearchResultItemsTorrentContentContentAttributesContentAttribute) GetKey() string {
	return v.Key
}

// GetSource returns TorrentContentTorrentContentByIDIdTorrentContentSearchResultItemsTorrentContentContentAttributesContentAttribute.Source, and is useful for accessing the field via an interface.
func (v *TorrentContentTorrentContentByIDIdTorrentContentSearchResultItemsTorrentContentContentAttributesContentAttribute) GetSource() string {
	return v.Source
}

// GetValue returns TorrentContentTorrentContentByIDIdTorrentContentSearchResultItemsTorrentContentContentAttributesContentAttribute.Value, and is useful for accessing the field via an interface.
func (v *TorrentContentTorrentContentByIDIdTorrentContentSearchResultItemsTorrentContentContentAttributesContentAttribute) GetValue() string {
	return v.Value
}

// TorrentContentTorrentContentByIDIdTorrentContentSearchResultItemsTorrentContentEpisodes includes the requested fields of the GraphQL type Episodes.
type TorrentContentTorrentContentByIDIdTorrentContentSearchResultItemsTorrentContentEpisodes struct {
	Seasons []TorrentContentTorrentContentByIDIdTorrentContentSearchResultItemsTorrentContentEpisodesSeasonsSeason `json:"seasons"`
}

// GetSeasons returns TorrentContentTorrentContentByIDIdTorrentContentSearchResultItemsTorrentContentEpisodes.Seasons, and is useful for accessing the field via an interface.
func (v *TorrentContentTorrentContentByIDIdTorrentContentSearchResultItemsTorrentContentEpisodes) GetSeasons() []TorrentContentTorrentContentByIDIdTorrentContentSearchResultItemsTorrentContentEpisodesSeasonsSeason {
	return v.Seasons
}

// TorrentContentTorrentContentByIDIdTorrentContentSearchResultItemsTorrentContentEpisodesSeasonsSeason includes the requested fields of the GraphQL type Season.
type TorrentContentTorrentContentByIDIdTorrentContentSearchResultItemsTorrentContentEpisodesSeasonsSeason struct {
	Season   int   `json:"season"`
	Episodes []int `json:"episodes"`
}

// GetSeason returns TorrentContentTorrentContentByIDIdTorrentContentSearchResultItemsTorrentContentEpisodesSeasonsSeason.Season, and is useful for accessing the field via an interface.
func (v *TorrentContentTorrentContentByIDIdTorrentContentSearchResultItemsTorrentContentEpisodesSeasonsSeason) GetSeason() int {
	return v.Season
}

// GetEpisodes returns TorrentContentTorrentContentByIDIdTorrentContentSearchResultItemsTorrentContentEpisodesSeasonsSeason.Episodes, and is useful for accessing the field via an interface.
func (v *TorrentContentTorrentContentByIDIdTorrentContentSearchResultItemsTorrentContentEpisodesSeasonsSeason) GetEpisodes() []int {
	return v.Episodes
}

// TorrentContentTorrentContentByIDIdTorrentContentSearchResultItemsTorrentContentTorrent includes the requested fields of the GraphQL type Torrent.
type TorrentContentTorrentContentByIDIdTorrentContentSearchResultItemsTorrentContentTorrent struct {
	MagnetUri string `json:"magnetUri"`
}

// GetMagnetUri returns TorrentContentTorrentContentByIDIdTorrentContentSearchResultItemsTorrentContentTorrent.MagnetUri, and is useful for accessing the field via an interface.
func (v *TorrentContentTorrentContentByIDIdTorrentContentSearchResultItemsTorrentContentTorrent) GetMagnetUri() string {
	return v.MagnetUri
}

// __TorrentContentInput is used internally by genqlient
type __TorrentContentInput struct {
	InfoHash protocol.ID `json:"infoHash"`
}

// GetInfoHash returns __TorrentContentInput.InfoHash, and is useful for accessing the field via an interface.
func (v *__TorrentContentInput) GetInfoHash() protocol.ID { return v.InfoHash }

// The query or mutation executed by TorrentContent.
const TorrentContent_Operation = `
query TorrentContent ($infoHash: Hash20) {
	torrentContentByID {
		id(infoHash: $infoHash) {
			items {
				infoHash
				torrent {
					magnetUri
				}
				contentType
				content {
					id
					source
					attributes {
						key
						source
						value
					}
				}
				episodes {
					seasons {
						season
						episodes
					}
				}
			}
		}
	}
}
`

func TorrentContent(
	ctx_ context.Context,
	client_ graphql.Client,
	infoHash protocol.ID,
) (*TorrentContentResponse, error) {
	req_ := &graphql.Request{
		OpName: "TorrentContent",
		Query:  TorrentContent_Operation,
		Variables: &__TorrentContentInput{
			InfoHash: infoHash,
		},
	}
	var err_ error

	var data_ TorrentContentResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}
